spring.application.name=job-application-tracker

spring.datasource.url=jdbc:mysql://localhost:3306/job_application_tracker
spring.datasource.username=root
spring.datasource.password=snehagoyal@13

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true